### PR TITLE
Developer's Certification of Origin

### PR DESCRIPTION
**Pull request by mikemill**
Adding a DCO file to be used with contribution sign-offs.

Signed-off-by: Michael Miller mikemill@gmail.com

### CODE REVIEW

**Comment by jdarwood007** [comment]
Just added a comment but is the c item supposed to be recursive?

**Comment by mikemill** [comment]
Let's say that I got it from you who in turn got it from Norv, who in turn got it from Spuds.  If you and/or Norv were to sign off on it then you'd both be doing it under (c).

**Comment by jdarwood007** [comment]
Ok, just making sure it wasn't a mistake or something.  That does make sense though.  Do we need to resolve a & b then or trust it?  Or should a or b have signed off as well?

**Comment by mikemill** [comment]
First let me say that the text is from the Linux Kernel's DCO.  What do you mean by resolving a or b?  With our current channels (c) really won't come up.  It'll committing a merge request which really doesn't need a sign-off.  If we want to come up with a full set of procedures we can but I think some common sense works.  I'd pretty much follow the Linux Kernel's procedures as a guide: http://git.kernel.org/?p=linux/kernel/git/torvalds/linux-2.6.git;a=blob;f=Documentation/SubmittingPatches  So if someone submits a patch and all you are doing is committing that patch then you don't need to sign off on it (the patch submitter does though).  If you need to modify the patch then you add a note and sign off on it.

**Comment by norv** [comment]
It simply refers to a bit longer chain: you have received it from someone who certifies c) to you, and pass it over to Spuds. For whom you're also under c) case. You: have it under c), yourself, and offer it under c).

**Comment by jdarwood007** [comment]
Do we have to make sure the person or entity under c (down though the line as needed) is agreed on a or b?.  Or do we just trust that the person under c is trustworthy enough?

What I am thinking about is miscommunications of a license or allowance of code usage.  Where c is used but shouldn't of as a/b was not really agreed upon.

Do we have a/b sign off as well as c?  Such as this commit I would also sign off if I was the one committing it under c in addition to Mike

**Comment by mikemill** [comment]
The person signing off is certifying that their submission is within the scope of the DCO.  If you don't trust the person then you reject the patch.  End of story.

In reality we aren't going to have long chains of people using (c).  The majority of cases are going to be "person commits to their repo, pushes to their github, open merge request, and then a committer merges it into the main repo".  

The only time I see c coming into use is if someone posts a code change on the forum and we ask and get permission to include it.

But at the end of the day it comes down to trust.  If you don't trust that the person is being honest in their certification then reject the patch.

**Pull request merged**
